require 'opentok'

# Values below should be entered as strings
OPENTOK_API_KEY = ENV['OPENTOK_API_KEY']                
OPENTOK_API_SECRET = ENV['OPENTOK_API_SECRET']                         
OPENTOK_SDK = OpenTok::OpenTokSDK.new OPENTOK_API_KEY, OPENTOK_API_SECRET

GOOGLE_CLIENT_ID = ENV['GOOGLE_CLIENT_ID']  
GOOGLE_CLIENT_SECRET = ENV['GOOGLE_CLIENT_SECRET']  
GOOGLE_REFRESH_TOKEN = ENV['GOOGLE_REFRESH_TOKEN']  

FACEBOOK_API_KEY = ENV['FACEBOOK_API_KEY']
FACEBOOK_API_SECRET = ENV['FACEBOOK_API_SECRET']

LINKEDIN_API_KEY = ENV['LINKEDIN_API_KEY']
LINKEDIN_API_SECRET = ENV['LINKEDIN_API_SECRET']